// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: OpenHT_UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void fan_speed_value(lv_event_t * e);
void on_xmit_button_press(lv_event_t * e);
void on_xmit_button_release(lv_event_t * e);
void on_screen_pressed(lv_event_t * e);
void on_rx_click(lv_event_t * e);
void on_tx_click(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
