// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: OpenHT_UI

#include "openht_ui.h"
#include "../lvgl_ui/ui.h"

void fan_speed_value(lv_event_t * e)
{
	// Your code here
}
