// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenHT_UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void on_about_clicked(lv_event_t * e);
void on_callsign_clicked(lv_event_t * e);
void on_mode_clicked(lv_event_t * e);
void on_settings_clicked(lv_event_t * e);
void on_fpga_status_clicked(lv_event_t * e);
void on_freq_click(lv_event_t * e);
void on_xmit_button_press(lv_event_t * e);
void on_xmit_button_release(lv_event_t * e);
void on_vol_changed(lv_event_t * e);
void on_mic_changed(lv_event_t * e);
void on_screen_pressed(lv_event_t * e);
void on_freq_button_down_press(lv_event_t * e);
void on_freq_button_down_press(lv_event_t * e);
void on_freq_button_up_press(lv_event_t * e);
void on_freq_button_up_press(lv_event_t * e);
void on_about_ok_clicked(lv_event_t * e);
void on_mode_ok_clicked(lv_event_t * e);
void on_mode_cancel_clicked(lv_event_t * e);
void on_settings_erase_usr_clicked(lv_event_t * e);
void on_settings_reboot_clicked(lv_event_t * e);
void on_settings_erase_radio_clicked(lv_event_t * e);
void on_settings_load_fpga_clicked(lv_event_t * e);
void on_settings_erase_fpga_clicked(lv_event_t * e);
void on_use_soft_ptt_clicked(lv_event_t * e);
void on_use_tx_offset_clicked(lv_event_t * e);
void on_disp_brightness_changed(lv_event_t * e);
void on_settings_a_clicked(lv_event_t * e);
void on_settings_b_clicked(lv_event_t * e);
void on_settings_c_clicked(lv_event_t * e);
void on_settings_d_clicked(lv_event_t * e);
void on_settings_e_clicked(lv_event_t * e);
void on_settings_f_clicked(lv_event_t * e);
void on_split_txrx_clicked(lv_event_t * e);
void on_xcvr_settings_reset_clicked(lv_event_t * e);
void on_settings_ok_clicked(lv_event_t * e);
void on_callsign_ok_clicked(lv_event_t * e);
void on_callsign_cancel_clicked(lv_event_t * e);
void on_callsign_ta_click(lv_event_t * e);
void on_freq_change_panel_click(lv_event_t * e);
void on_freq_ok_clicked(lv_event_t * e);
void on_freq_cancel_clicked(lv_event_t * e);
void on_rx_freq_ta_click(lv_event_t * e);
void on_tx_freq_ta_click(lv_event_t * e);
void on_split_txrx_clicked(lv_event_t * e);
void on_split_txrx_clicked(lv_event_t * e);
void on_split_txrx_clicked(lv_event_t * e);
void on_split_txrx_clicked(lv_event_t * e);
void on_split_txrx_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
