// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.2
// LVGL version: 8.3.4
// Project name: OpenHT_UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_home_screen;
lv_obj_t * ui_home_screen_header_panel;
void ui_event_title_image(lv_event_t * e);
lv_obj_t * ui_title_image;
lv_obj_t * ui_battery_image;
lv_obj_t * ui_signal_strenth_image;
void ui_event_header_callsign_button(lv_event_t * e);
lv_obj_t * ui_header_callsign_button;
lv_obj_t * ui_header_callsign_label;
void ui_event_header_mode_button(lv_event_t * e);
lv_obj_t * ui_header_mode_button;
lv_obj_t * ui_header_mode_label;
void ui_event_header_settings_button(lv_event_t * e);
lv_obj_t * ui_header_settings_button;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label_Slider;
void ui_event_vol_slider(lv_event_t * e);
lv_obj_t * ui_vol_slider;
void ui_event_transmit_button(lv_event_t * e);
lv_obj_t * ui_transmit_button;
lv_obj_t * ui_Label3;
void ui_event_about_button(lv_event_t * e);
lv_obj_t * ui_about_button;
lv_obj_t * ui_Label5;
void ui_event_vfo_panel(lv_event_t * e);
lv_obj_t * ui_vfo_panel;
lv_obj_t * ui_label_test_rx;
lv_obj_t * ui_label_test_tx;
void ui_event_screen_num_freq_pads(lv_event_t * e);
lv_obj_t * ui_screen_num_freq_pads;
lv_obj_t * ui_qwerty_key_panel;
lv_obj_t * ui_freq_key_panel;
lv_obj_t * ui_panel_freq_bump;
void ui_event_freq_button_down(lv_event_t * e);
lv_obj_t * ui_freq_button_down;
lv_obj_t * ui_Label4;
void ui_event_freq_button_up(lv_event_t * e);
lv_obj_t * ui_freq_button_up;
lv_obj_t * ui_Label1;
lv_obj_t * ui_freq_dropdown;
lv_obj_t * ui_screen_scratchpad_1;
lv_obj_t * ui_about_panel;
lv_obj_t * ui_about_tab_panel;
lv_obj_t * ui_about_text_area;
lv_obj_t * ui_about_hw_text_area;
void ui_event_about_ok_btn(lv_event_t * e);
lv_obj_t * ui_about_ok_btn;
lv_obj_t * ui_Label6;
lv_obj_t * ui_about_logo;
lv_obj_t * ui_about_openht_logo;
lv_obj_t * ui_Label9;
lv_obj_t * ui_screen_scratchpad_2;
lv_obj_t * ui_mode_change_panel;
lv_obj_t * ui_mode_roller;
void ui_event_mode_ok_button(lv_event_t * e);
lv_obj_t * ui_mode_ok_button;
lv_obj_t * ui_Label7;
void ui_event_mode_cancel_button(lv_event_t * e);
lv_obj_t * ui_mode_cancel_button;
lv_obj_t * ui_Label8;
lv_obj_t * ui_screen_scratchpad_3;
lv_obj_t * ui_settings_panel;
void ui_event_settings_erase_user_btn(lv_event_t * e);
lv_obj_t * ui_settings_erase_user_btn;
lv_obj_t * ui_Label11;
void ui_event_settings_load_fpga_btn(lv_event_t * e);
lv_obj_t * ui_settings_load_fpga_btn;
lv_obj_t * ui_Label12;
void ui_event_settings_erase_fpga_btn(lv_event_t * e);
lv_obj_t * ui_settings_erase_fpga_btn;
lv_obj_t * ui_Label13;
void ui_event_settings_a_btn(lv_event_t * e);
lv_obj_t * ui_settings_a_btn;
lv_obj_t * ui_Label14;
void ui_event_settings_b_btn(lv_event_t * e);
lv_obj_t * ui_settings_b_btn;
lv_obj_t * ui_Label16;
void ui_event_settings_c_btn(lv_event_t * e);
lv_obj_t * ui_settings_c_btn;
lv_obj_t * ui_Label15;
void ui_event_settings_d_btn(lv_event_t * e);
lv_obj_t * ui_settings_d_btn;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label18;
void ui_event_use_freq_offset_cb(lv_event_t * e);
lv_obj_t * ui_use_freq_offset_cb;
void ui_event_display_brightness_slider(lv_event_t * e);
lv_obj_t * ui_display_brightness_slider;
void ui_event_settings_ok_btn(lv_event_t * e);
lv_obj_t * ui_settings_ok_btn;
lv_obj_t * ui_Label10;
lv_obj_t * ui_screen_scratchpad_4;
lv_obj_t * ui_callsign_change_panel;
void ui_event_callsign_ok_btn(lv_event_t * e);
lv_obj_t * ui_callsign_ok_btn;
lv_obj_t * ui_Label19;
void ui_event_callsign_cancel_btn(lv_event_t * e);
lv_obj_t * ui_callsign_cancel_btn;
lv_obj_t * ui_Label20;
void ui_event_text_area_callsign(lv_event_t * e);
lv_obj_t * ui_text_area_callsign;
lv_obj_t * ui_screen_scratchpad_5;
void ui_event_freq_change_panel(lv_event_t * e);
lv_obj_t * ui_freq_change_panel;
void ui_event_freq_ok_btn(lv_event_t * e);
lv_obj_t * ui_freq_ok_btn;
lv_obj_t * ui_Label21;
void ui_event_freq_cancel_btn(lv_event_t * e);
lv_obj_t * ui_freq_cancel_btn;
lv_obj_t * ui_Label22;
lv_obj_t * ui_rx_freq_panel;
lv_obj_t * ui_label_rx;
void ui_event_rx_freq_ta(lv_event_t * e);
lv_obj_t * ui_rx_freq_ta;
lv_obj_t * ui_tx_freq_panel;
lv_obj_t * ui_label_tx;
void ui_event_tx_freq_ta(lv_event_t * e);
lv_obj_t * ui_tx_freq_ta;
lv_obj_t * ui_offset_tx_panel;
lv_obj_t * ui_label_tx1;
lv_obj_t * ui_tx_offset_ta;
void ui_event_split_freq_cb(lv_event_t * e);
lv_obj_t * ui_split_freq_cb;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_title_image(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        on_about_clicked(e);
    }
}
void ui_event_header_callsign_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_callsign_clicked(e);
    }
}
void ui_event_header_mode_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_mode_clicked(e);
    }
}
void ui_event_header_settings_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_clicked(e);
    }
}
void ui_event_vol_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_vol_changed(e);
    }
}
void ui_event_transmit_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        on_xmit_button_press(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        on_xmit_button_release(e);
    }
}
void ui_event_about_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_about_clicked(e);
    }
}
void ui_event_vfo_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_freq_click(e);
    }
}
void ui_event_screen_num_freq_pads(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        _ui_screen_change(ui_home_screen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0);
    }
    if(event_code == LV_EVENT_PRESSED) {
        on_screen_pressed(e);
    }
}
void ui_event_freq_button_down(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        on_freq_button_down_press(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        on_freq_button_down_press(e);
    }
}
void ui_event_freq_button_up(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        on_freq_button_up_press(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        on_freq_button_up_press(e);
    }
}
void ui_event_about_ok_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_about_ok_clicked(e);
    }
}
void ui_event_mode_ok_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_mode_ok_clicked(e);
    }
}
void ui_event_mode_cancel_button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_mode_cancel_clicked(e);
    }
}
void ui_event_settings_erase_user_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_erase_usr_clicked(e);
    }
}
void ui_event_settings_load_fpga_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_load_fpga_clicked(e);
    }
}
void ui_event_settings_erase_fpga_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_erase_fpga_clicked(e);
    }
}
void ui_event_settings_a_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_a_clicked(e);
    }
}
void ui_event_settings_b_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_b_clicked(e);
    }
}
void ui_event_settings_c_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_c_clicked(e);
    }
}
void ui_event_settings_d_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_d_clicked(e);
    }
}
void ui_event_use_freq_offset_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_use_tx_offset_clicked(e);
    }
}
void ui_event_display_brightness_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        on_disp_brightness_changed(e);
    }
}
void ui_event_settings_ok_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_settings_ok_clicked(e);
    }
}
void ui_event_callsign_ok_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_callsign_ok_clicked(e);
    }
}
void ui_event_callsign_cancel_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_callsign_cancel_clicked(e);
    }
}
void ui_event_text_area_callsign(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_callsign_ta_click(e);
    }
}
void ui_event_freq_change_panel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_freq_change_panel_click(e);
    }
}
void ui_event_freq_ok_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_freq_ok_clicked(e);
    }
}
void ui_event_freq_cancel_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_freq_cancel_clicked(e);
    }
}
void ui_event_rx_freq_ta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_rx_freq_ta_click(e);
    }
}
void ui_event_tx_freq_ta(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_tx_freq_ta_click(e);
    }
}
void ui_event_split_freq_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        on_split_txrx_clicked(e);
    }
}

///////////////////// SCREENS ////////////////////
void ui_home_screen_screen_init(void)
{
    ui_home_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_home_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_home_screen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_home_screen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_screen_header_panel = lv_obj_create(ui_home_screen);
    lv_obj_set_height(ui_home_screen_header_panel, 100);
    lv_obj_set_width(ui_home_screen_header_panel, lv_pct(100));
    lv_obj_set_align(ui_home_screen_header_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_home_screen_header_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_home_screen_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_home_screen_header_panel, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_home_screen_header_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_home_screen_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_home_screen_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_home_screen_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_home_screen_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_home_screen_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title_image = lv_img_create(ui_home_screen_header_panel);
    lv_img_set_src(ui_title_image, &ui_img_openht_logo_w_png);
    lv_obj_set_width(ui_title_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title_image, 0);
    lv_obj_set_y(ui_title_image, 1);
    lv_obj_set_align(ui_title_image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_title_image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_title_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery_image = lv_img_create(ui_home_screen_header_panel);
    lv_img_set_src(ui_battery_image, &ui_img_152149816);
    lv_obj_set_width(ui_battery_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery_image, -20);
    lv_obj_set_y(ui_battery_image, 5);
    lv_obj_set_align(ui_battery_image, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_battery_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_signal_strenth_image = lv_img_create(ui_home_screen_header_panel);
    lv_img_set_src(ui_signal_strenth_image, &ui_img_492966190);
    lv_obj_set_width(ui_signal_strenth_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signal_strenth_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signal_strenth_image, 15);
    lv_obj_set_y(ui_signal_strenth_image, 5);
    lv_obj_add_flag(ui_signal_strenth_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_signal_strenth_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header_callsign_button = lv_btn_create(ui_home_screen_header_panel);
    lv_obj_set_width(ui_header_callsign_button, 200);
    lv_obj_set_height(ui_header_callsign_button, 50);
    lv_obj_set_align(ui_header_callsign_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_header_callsign_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_header_callsign_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_callsign_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_callsign_label = lv_label_create(ui_header_callsign_button);
    lv_obj_set_width(ui_header_callsign_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_header_callsign_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_header_callsign_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_header_callsign_label, "Callsign: ");
    lv_obj_set_style_text_color(ui_header_callsign_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_header_callsign_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_header_callsign_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_mode_button = lv_btn_create(ui_home_screen_header_panel);
    lv_obj_set_height(ui_header_mode_button, 50);
    lv_obj_set_width(ui_header_mode_button, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_header_mode_button, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_header_mode_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_header_mode_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_mode_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_mode_label = lv_label_create(ui_header_mode_button);
    lv_obj_set_width(ui_header_mode_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_header_mode_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_header_mode_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_header_mode_label, "Mode: ");
    lv_obj_set_style_text_color(ui_header_mode_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_header_mode_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_header_mode_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_settings_button = lv_btn_create(ui_home_screen_header_panel);
    lv_obj_set_width(ui_header_settings_button, 50);
    lv_obj_set_height(ui_header_settings_button, 50);
    lv_obj_set_x(ui_header_settings_button, -60);
    lv_obj_set_y(ui_header_settings_button, 1);
    lv_obj_set_align(ui_header_settings_button, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_header_settings_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_header_settings_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_settings_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_header_settings_button);
    lv_img_set_src(ui_Image1, &ui_img_gear_w_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -5);
    lv_obj_set_align(ui_Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 210);
    lv_obj_set_align(ui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label2, "VFO");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Slider = lv_label_create(ui_home_screen);
    lv_obj_set_width(ui_Label_Slider, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Slider, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Slider, -15);
    lv_obj_set_y(ui_Label_Slider, -68);
    lv_obj_set_align(ui_Label_Slider, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Label_Slider, "Volume Control");
    lv_obj_set_style_text_color(ui_Label_Slider, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label_Slider, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_Slider, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vol_slider = lv_slider_create(ui_home_screen);
    lv_slider_set_value(ui_vol_slider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_vol_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_vol_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_vol_slider, 350);
    lv_obj_set_height(ui_vol_slider, 20);
    lv_obj_set_x(ui_vol_slider, 0);
    lv_obj_set_y(ui_vol_slider, -22);
    lv_obj_set_align(ui_vol_slider, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_vol_slider, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_vol_slider, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vol_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_vol_slider, lv_color_hex(0x1E242D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_vol_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_vol_slider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_vol_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_vol_slider, lv_color_hex(0x37B9F5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vol_slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_vol_slider, lv_color_hex(0x1464F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_vol_slider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_vol_slider, lv_color_hex(0x5F6464), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vol_slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_vol_slider, lv_color_hex(0x3C424B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_vol_slider, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_vol_slider, lv_color_hex(0x373C46), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_vol_slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_vol_slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_vol_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_vol_slider, lv_color_hex(0x0096FF), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_vol_slider, 255, LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_vol_slider, 4, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_transmit_button = lv_btn_create(ui_home_screen);
    lv_obj_set_width(ui_transmit_button, 145);
    lv_obj_set_height(ui_transmit_button, 123);
    lv_obj_set_x(ui_transmit_button, 1);
    lv_obj_set_y(ui_transmit_button, 183);
    lv_obj_set_align(ui_transmit_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_transmit_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_transmit_button, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_transmit_button, 400, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_transmit_button, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_transmit_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_transmit_button, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_transmit_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_transmit_button, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_transmit_button, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_transmit_button, lv_color_hex(0xD4001D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_transmit_button, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_transmit_button);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "PTT");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_button = lv_btn_create(ui_home_screen);
    lv_obj_set_width(ui_about_button, 130);
    lv_obj_set_height(ui_about_button, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_about_button, 339);
    lv_obj_set_y(ui_about_button, -259);
    lv_obj_set_align(ui_about_button, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_about_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_about_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_about_button, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_about_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_about_button, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_about_button, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_about_button);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "About...");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vfo_panel = lv_obj_create(ui_home_screen);
    lv_obj_set_width(ui_vfo_panel, 450);
    lv_obj_set_height(ui_vfo_panel, 125);
    lv_obj_set_x(ui_vfo_panel, 0);
    lv_obj_set_y(ui_vfo_panel, 250);
    lv_obj_set_align(ui_vfo_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_vfo_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vfo_panel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vfo_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vfo_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_vfo_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_vfo_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_rx = lv_label_create(ui_vfo_panel);
    lv_obj_set_width(ui_label_test_rx, 400);
    lv_obj_set_height(ui_label_test_rx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_test_rx, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_label_test_rx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_test_rx, "000.000.000");
    lv_obj_set_style_text_color(ui_label_test_rx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_test_rx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label_test_rx, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_test_rx, &ui_font_number_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_tx = lv_label_create(ui_vfo_panel);
    lv_obj_set_width(ui_label_test_tx, 400);
    lv_obj_set_height(ui_label_test_tx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_tx, 0);
    lv_obj_set_y(ui_label_test_tx, 50);
    lv_obj_set_align(ui_label_test_tx, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_label_test_tx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_test_tx, "000.000.000");
    lv_obj_set_style_text_color(ui_label_test_tx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_test_tx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label_test_tx, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_test_tx, &ui_font_number_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_title_image, ui_event_title_image, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_header_callsign_button, ui_event_header_callsign_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_header_mode_button, ui_event_header_mode_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_header_settings_button, ui_event_header_settings_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vol_slider, ui_event_vol_slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_transmit_button, ui_event_transmit_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_about_button, ui_event_about_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vfo_panel, ui_event_vfo_panel, LV_EVENT_ALL, NULL);

}
void ui_screen_num_freq_pads_screen_init(void)
{
    ui_screen_num_freq_pads = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_num_freq_pads, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_qwerty_key_panel = lv_obj_create(ui_screen_num_freq_pads);
    lv_obj_set_height(ui_qwerty_key_panel, 470);
    lv_obj_set_width(ui_qwerty_key_panel, lv_pct(100));
    lv_obj_set_x(ui_qwerty_key_panel, 0);
    lv_obj_set_y(ui_qwerty_key_panel, 330);
    lv_obj_clear_flag(ui_qwerty_key_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_qwerty_key_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_qwerty_key_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_qwerty_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_qwerty_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_qwerty_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_qwerty_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_qwerty_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_qwerty_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_key_panel = lv_obj_create(ui_screen_num_freq_pads);
    lv_obj_set_height(ui_freq_key_panel, 495);
    lv_obj_set_width(ui_freq_key_panel, lv_pct(100));
    lv_obj_set_x(ui_freq_key_panel, 0);
    lv_obj_set_y(ui_freq_key_panel, 305);
    lv_obj_clear_flag(ui_freq_key_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_key_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_key_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_freq_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_freq_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_freq_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_freq_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_freq_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_freq_key_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panel_freq_bump = lv_obj_create(ui_freq_key_panel);
    lv_obj_set_height(ui_panel_freq_bump, 60);
    lv_obj_set_width(ui_panel_freq_bump, lv_pct(90));
    lv_obj_set_x(ui_panel_freq_bump, 0);
    lv_obj_set_y(ui_panel_freq_bump, 5);
    lv_obj_set_align(ui_panel_freq_bump, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_panel_freq_bump, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panel_freq_bump, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panel_freq_bump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_panel_freq_bump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_panel_freq_bump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_panel_freq_bump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_panel_freq_bump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_panel_freq_bump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_panel_freq_bump, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_button_down = lv_btn_create(ui_panel_freq_bump);
    lv_obj_set_width(ui_freq_button_down, 130);
    lv_obj_set_height(ui_freq_button_down, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_freq_button_down, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_freq_button_down, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_freq_button_down, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_button_down, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_button_down, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_freq_button_down, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_freq_button_down, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label4 = lv_label_create(ui_freq_button_down);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "-");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_button_up = lv_btn_create(ui_panel_freq_bump);
    lv_obj_set_width(ui_freq_button_up, 130);
    lv_obj_set_height(ui_freq_button_up, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_freq_button_up, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_freq_button_up, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_freq_button_up, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_button_up, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_button_up, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_freq_button_up, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_freq_button_up, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label1 = lv_label_create(ui_freq_button_up);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "+");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_dropdown = lv_dropdown_create(ui_panel_freq_bump);
    lv_dropdown_set_options(ui_freq_dropdown, "6.25 kHz\n12.5 kHz\n25 kHz");
    lv_obj_set_width(ui_freq_dropdown, 150);
    lv_obj_set_height(ui_freq_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_freq_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_freq_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_freq_dropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_freq_dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_freq_dropdown, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_freq_dropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_freq_dropdown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_freq_dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_freq_dropdown), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_freq_dropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_freq_dropdown), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_freq_dropdown), lv_color_hex(0x464B50),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_freq_dropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_freq_dropdown), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_freq_dropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_freq_button_down, ui_event_freq_button_down, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_freq_button_up, ui_event_freq_button_up, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen_num_freq_pads, ui_event_screen_num_freq_pads, LV_EVENT_ALL, NULL);

}
void ui_screen_scratchpad_1_screen_init(void)
{
    ui_screen_scratchpad_1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_scratchpad_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_about_panel = lv_obj_create(ui_screen_scratchpad_1);
    lv_obj_set_width(ui_about_panel, 420);
    lv_obj_set_height(ui_about_panel, 660);
    lv_obj_set_align(ui_about_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_about_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_grad_color(ui_about_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_about_panel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_about_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_about_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_tab_panel = lv_obj_create(ui_about_panel);
    lv_obj_set_width(ui_about_tab_panel, 400);
    lv_obj_set_height(ui_about_tab_panel, 430);
    lv_obj_set_x(ui_about_tab_panel, 0);
    lv_obj_set_y(ui_about_tab_panel, 35);
    lv_obj_set_align(ui_about_tab_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_about_tab_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_about_tab_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_about_tab_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_about_tab_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_about_tab_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_about_tab_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_about_tab_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_about_tab_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_text_area = lv_textarea_create(ui_about_tab_panel);
    lv_obj_set_width(ui_about_text_area, lv_pct(100));
    lv_obj_set_height(ui_about_text_area, lv_pct(100));
    lv_textarea_set_text(ui_about_text_area,
                         "OpenHT is an Open Source handheld two-way radio designed by and for Amateur Radio operators. It showcases freely available open source digital protocols for voice and data. FreeDV and M17 are first class citizens with additional support for FM/AM/SSB.\n\nThis is the Unicorn you've been waiting for, so what are you waiting for?\n\n73,\nM17 Project");
    lv_obj_clear_flag(ui_about_text_area,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_about_text_area, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_about_text_area, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_about_text_area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_about_text_area, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_about_text_area, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_about_text_area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_about_text_area, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_hw_text_area = lv_textarea_create(ui_about_tab_panel);
    lv_obj_set_width(ui_about_hw_text_area, lv_pct(100));
    lv_obj_set_height(ui_about_hw_text_area, lv_pct(100));
    lv_textarea_set_text(ui_about_hw_text_area,
                         "MCU: STM32F469I\nFPGA: Lattice LIFCL-40\n\nBands Supported:\n1: 389.5-510 MHz\n2: 779-1020 MHz\n3: 2400- 2483.5 MHz\n\nModes Supported:\n1: M17 (http://m17project.org)\n2: FreeDV (http://freedv.org)\n3: NFM/FM\n4: AM/SSB\n5: TBD");
    lv_obj_add_flag(ui_about_hw_text_area, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_about_hw_text_area,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_about_hw_text_area, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_about_hw_text_area, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_about_hw_text_area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_about_hw_text_area, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_about_hw_text_area, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_about_hw_text_area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_about_hw_text_area, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_ok_btn = lv_btn_create(ui_about_panel);
    lv_obj_set_width(ui_about_ok_btn, 100);
    lv_obj_set_height(ui_about_ok_btn, 50);
    lv_obj_set_align(ui_about_ok_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_about_ok_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_about_ok_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_about_ok_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_about_ok_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_about_ok_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_about_ok_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label6 = lv_label_create(ui_about_ok_btn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "OK");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_logo = lv_img_create(ui_about_panel);
    lv_img_set_src(ui_about_logo, &ui_img_m17_logo_sm_png);
    lv_obj_set_width(ui_about_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_about_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_about_logo, 20);
    lv_obj_set_y(ui_about_logo, 10);
    lv_obj_add_flag(ui_about_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_about_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_about_logo, 400);

    ui_about_openht_logo = lv_img_create(ui_about_panel);
    lv_img_set_src(ui_about_openht_logo, &ui_img_openht_logo_png);
    lv_obj_set_width(ui_about_openht_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_about_openht_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_about_openht_logo, 62);
    lv_obj_set_y(ui_about_openht_logo, -278);
    lv_obj_set_align(ui_about_openht_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_about_openht_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_about_openht_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_about_panel);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 102);
    lv_obj_set_y(ui_Label9, -227);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "FW ver 0.0.1\nFPGA ver: 1337\nBuild Date: 230401");

    lv_obj_add_event_cb(ui_about_ok_btn, ui_event_about_ok_btn, LV_EVENT_ALL, NULL);

}
void ui_screen_scratchpad_2_screen_init(void)
{
    ui_screen_scratchpad_2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_scratchpad_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mode_change_panel = lv_obj_create(ui_screen_scratchpad_2);
    lv_obj_set_width(ui_mode_change_panel, 323);
    lv_obj_set_height(ui_mode_change_panel, 379);
    lv_obj_set_align(ui_mode_change_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mode_change_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mode_change_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mode_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mode_change_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mode_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode_roller = lv_roller_create(ui_mode_change_panel);
    lv_obj_set_height(ui_mode_roller, 254);
    lv_obj_set_width(ui_mode_roller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mode_roller, 0);
    lv_obj_set_y(ui_mode_roller, -30);
    lv_obj_set_align(ui_mode_roller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_mode_roller, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mode_roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mode_roller, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mode_roller, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mode_roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_mode_roller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_mode_roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode_ok_button = lv_btn_create(ui_mode_change_panel);
    lv_obj_set_width(ui_mode_ok_button, 100);
    lv_obj_set_height(ui_mode_ok_button, 50);
    lv_obj_set_x(ui_mode_ok_button, 66);
    lv_obj_set_y(ui_mode_ok_button, -1);
    lv_obj_set_align(ui_mode_ok_button, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_mode_ok_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mode_ok_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mode_ok_button, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mode_ok_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mode_ok_button, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_mode_ok_button, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label7 = lv_label_create(ui_mode_ok_button);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "OK");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mode_cancel_button = lv_btn_create(ui_mode_change_panel);
    lv_obj_set_width(ui_mode_cancel_button, 100);
    lv_obj_set_height(ui_mode_cancel_button, 50);
    lv_obj_set_x(ui_mode_cancel_button, -48);
    lv_obj_set_y(ui_mode_cancel_button, -1);
    lv_obj_set_align(ui_mode_cancel_button, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_mode_cancel_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mode_cancel_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mode_cancel_button, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mode_cancel_button, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_mode_cancel_button, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_mode_cancel_button, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label8 = lv_label_create(ui_mode_cancel_button);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Cancel");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_mode_ok_button, ui_event_mode_ok_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mode_cancel_button, ui_event_mode_cancel_button, LV_EVENT_ALL, NULL);

}
void ui_screen_scratchpad_3_screen_init(void)
{
    ui_screen_scratchpad_3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_scratchpad_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_panel = lv_obj_create(ui_screen_scratchpad_3);
    lv_obj_set_width(ui_settings_panel, 420);
    lv_obj_set_height(ui_settings_panel, 660);
    lv_obj_set_x(ui_settings_panel, 0);
    lv_obj_set_y(ui_settings_panel, 50);
    lv_obj_set_align(ui_settings_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_settings_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_settings_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_settings_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_erase_user_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_erase_user_btn, 261);
    lv_obj_set_height(ui_settings_erase_user_btn, 50);
    lv_obj_add_flag(ui_settings_erase_user_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_erase_user_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_erase_user_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_erase_user_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_erase_user_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_erase_user_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label11 = lv_label_create(ui_settings_erase_user_btn);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Erase User Settings");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_load_fpga_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_load_fpga_btn, 156);
    lv_obj_set_height(ui_settings_load_fpga_btn, 50);
    lv_obj_set_x(ui_settings_load_fpga_btn, 0);
    lv_obj_set_y(ui_settings_load_fpga_btn, 70);
    lv_obj_add_flag(ui_settings_load_fpga_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_load_fpga_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_load_fpga_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_load_fpga_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_load_fpga_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_load_fpga_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label12 = lv_label_create(ui_settings_load_fpga_btn);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Load FPGA");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_erase_fpga_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_erase_fpga_btn, 156);
    lv_obj_set_height(ui_settings_erase_fpga_btn, 50);
    lv_obj_set_x(ui_settings_erase_fpga_btn, 180);
    lv_obj_set_y(ui_settings_erase_fpga_btn, 70);
    lv_obj_add_flag(ui_settings_erase_fpga_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_erase_fpga_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_erase_fpga_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_erase_fpga_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_erase_fpga_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_erase_fpga_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label13 = lv_label_create(ui_settings_erase_fpga_btn);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Erase FPGA");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_a_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_a_btn, 156);
    lv_obj_set_height(ui_settings_a_btn, 50);
    lv_obj_set_x(ui_settings_a_btn, 0);
    lv_obj_set_y(ui_settings_a_btn, 140);
    lv_obj_add_flag(ui_settings_a_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_a_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_a_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_a_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_a_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_a_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label14 = lv_label_create(ui_settings_a_btn);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Button A");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_b_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_b_btn, 156);
    lv_obj_set_height(ui_settings_b_btn, 50);
    lv_obj_set_x(ui_settings_b_btn, 180);
    lv_obj_set_y(ui_settings_b_btn, 140);
    lv_obj_add_flag(ui_settings_b_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_b_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_b_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_b_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_b_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_b_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label16 = lv_label_create(ui_settings_b_btn);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Button B");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_c_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_c_btn, 156);
    lv_obj_set_height(ui_settings_c_btn, 50);
    lv_obj_set_x(ui_settings_c_btn, 0);
    lv_obj_set_y(ui_settings_c_btn, 210);
    lv_obj_add_flag(ui_settings_c_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_c_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_c_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_c_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_c_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_c_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label15 = lv_label_create(ui_settings_c_btn);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Button C");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_d_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_d_btn, 156);
    lv_obj_set_height(ui_settings_d_btn, 50);
    lv_obj_set_x(ui_settings_d_btn, 180);
    lv_obj_set_y(ui_settings_d_btn, 210);
    lv_obj_add_flag(ui_settings_d_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_d_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_d_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_d_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_d_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_d_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label17 = lv_label_create(ui_settings_d_btn);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Button D");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_settings_panel);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -80);
    lv_obj_set_y(ui_Label18, 452);
    lv_obj_set_align(ui_Label18, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label18, "Display Brightness:");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_use_freq_offset_cb = lv_checkbox_create(ui_settings_panel);
    lv_checkbox_set_text(ui_use_freq_offset_cb, "Use TX Frequency offset");
    lv_obj_set_width(ui_use_freq_offset_cb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_use_freq_offset_cb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_use_freq_offset_cb, -50);
    lv_obj_set_y(ui_use_freq_offset_cb, -12);
    lv_obj_set_align(ui_use_freq_offset_cb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_use_freq_offset_cb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_use_freq_offset_cb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_use_freq_offset_cb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_use_freq_offset_cb, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_use_freq_offset_cb, lv_color_hex(0x4E4E4E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_use_freq_offset_cb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_display_brightness_slider = lv_slider_create(ui_settings_panel);
    lv_slider_set_range(ui_display_brightness_slider, 0, 255);
    lv_slider_set_value(ui_display_brightness_slider, 127, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_display_brightness_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_display_brightness_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_display_brightness_slider, 350);
    lv_obj_set_height(ui_display_brightness_slider, 20);
    lv_obj_set_x(ui_display_brightness_slider, -1);
    lv_obj_set_y(ui_display_brightness_slider, -105);
    lv_obj_set_align(ui_display_brightness_slider, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_display_brightness_slider, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_bg_color(ui_display_brightness_slider, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_display_brightness_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_display_brightness_slider, lv_color_hex(0x1E242D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_display_brightness_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_display_brightness_slider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_display_brightness_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_display_brightness_slider, lv_color_hex(0x37B9F5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_display_brightness_slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_display_brightness_slider, lv_color_hex(0x1464F0),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_display_brightness_slider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_display_brightness_slider, lv_color_hex(0x5F6464), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_display_brightness_slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_display_brightness_slider, lv_color_hex(0x3C424B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_display_brightness_slider, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_display_brightness_slider, lv_color_hex(0x373C46), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_display_brightness_slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_display_brightness_slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_display_brightness_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_display_brightness_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_display_brightness_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_display_brightness_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_display_brightness_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_display_brightness_slider, lv_color_hex(0x0096FF), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_display_brightness_slider, 255, LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_display_brightness_slider, 4, LV_PART_KNOB | LV_STATE_PRESSED);

    ui_settings_ok_btn = lv_btn_create(ui_settings_panel);
    lv_obj_set_width(ui_settings_ok_btn, 100);
    lv_obj_set_height(ui_settings_ok_btn, 50);
    lv_obj_set_align(ui_settings_ok_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_settings_ok_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_ok_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings_ok_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_ok_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_ok_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_settings_ok_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label10 = lv_label_create(ui_settings_ok_btn);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "OK");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_settings_erase_user_btn, ui_event_settings_erase_user_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_load_fpga_btn, ui_event_settings_load_fpga_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_erase_fpga_btn, ui_event_settings_erase_fpga_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_a_btn, ui_event_settings_a_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_b_btn, ui_event_settings_b_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_c_btn, ui_event_settings_c_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_d_btn, ui_event_settings_d_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_use_freq_offset_cb, ui_event_use_freq_offset_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_display_brightness_slider, ui_event_display_brightness_slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_ok_btn, ui_event_settings_ok_btn, LV_EVENT_ALL, NULL);

}
void ui_screen_scratchpad_4_screen_init(void)
{
    ui_screen_scratchpad_4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_scratchpad_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_callsign_change_panel = lv_obj_create(ui_screen_scratchpad_4);
    lv_obj_set_width(ui_callsign_change_panel, 449);
    lv_obj_set_height(ui_callsign_change_panel, 237);
    lv_obj_set_x(ui_callsign_change_panel, 0);
    lv_obj_set_y(ui_callsign_change_panel, 50);
    lv_obj_set_align(ui_callsign_change_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_callsign_change_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_callsign_change_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_callsign_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_callsign_change_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_callsign_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_callsign_ok_btn = lv_btn_create(ui_callsign_change_panel);
    lv_obj_set_width(ui_callsign_ok_btn, 100);
    lv_obj_set_height(ui_callsign_ok_btn, 50);
    lv_obj_set_x(ui_callsign_ok_btn, 66);
    lv_obj_set_y(ui_callsign_ok_btn, -1);
    lv_obj_set_align(ui_callsign_ok_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_callsign_ok_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_callsign_ok_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_callsign_ok_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_callsign_ok_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_callsign_ok_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_callsign_ok_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label19 = lv_label_create(ui_callsign_ok_btn);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "OK");
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_callsign_cancel_btn = lv_btn_create(ui_callsign_change_panel);
    lv_obj_set_width(ui_callsign_cancel_btn, 100);
    lv_obj_set_height(ui_callsign_cancel_btn, 50);
    lv_obj_set_x(ui_callsign_cancel_btn, -48);
    lv_obj_set_y(ui_callsign_cancel_btn, -1);
    lv_obj_set_align(ui_callsign_cancel_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_callsign_cancel_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_callsign_cancel_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_callsign_cancel_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_callsign_cancel_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_callsign_cancel_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_callsign_cancel_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label20 = lv_label_create(ui_callsign_cancel_btn);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Cancel");
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_text_area_callsign = lv_textarea_create(ui_callsign_change_panel);
    lv_obj_set_width(ui_text_area_callsign, 390);
    lv_obj_set_height(ui_text_area_callsign, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_text_area_callsign, 10);
    lv_obj_set_y(ui_text_area_callsign, 44);
    lv_textarea_set_max_length(ui_text_area_callsign, 9);
    lv_textarea_set_placeholder_text(ui_text_area_callsign, "CALLSIGN...");
    lv_textarea_set_one_line(ui_text_area_callsign, true);
    lv_obj_clear_flag(ui_text_area_callsign, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_text_area_callsign, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_text_area_callsign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_text_area_callsign, &ui_font_number_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_text_area_callsign, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_text_area_callsign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_text_area_callsign, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_text_area_callsign, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_text_area_callsign, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_text_area_callsign, &ui_font_number_60, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_text_area_callsign, lv_color_hex(0x37B9F5), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_text_area_callsign, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_callsign_ok_btn, ui_event_callsign_ok_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_callsign_cancel_btn, ui_event_callsign_cancel_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_text_area_callsign, ui_event_text_area_callsign, LV_EVENT_ALL, NULL);

}
void ui_screen_scratchpad_5_screen_init(void)
{
    ui_screen_scratchpad_5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_scratchpad_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_freq_change_panel = lv_obj_create(ui_screen_scratchpad_5);
    lv_obj_set_width(ui_freq_change_panel, 480);
    lv_obj_set_height(ui_freq_change_panel, 430);
    lv_obj_set_x(ui_freq_change_panel, 0);
    lv_obj_set_y(ui_freq_change_panel, 50);
    lv_obj_set_align(ui_freq_change_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_freq_change_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_change_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_freq_change_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_freq_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_freq_change_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_freq_change_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_freq_change_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_freq_change_panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_ok_btn = lv_btn_create(ui_freq_change_panel);
    lv_obj_set_width(ui_freq_ok_btn, 100);
    lv_obj_set_height(ui_freq_ok_btn, 50);
    lv_obj_set_x(ui_freq_ok_btn, 66);
    lv_obj_set_y(ui_freq_ok_btn, -1);
    lv_obj_set_align(ui_freq_ok_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_freq_ok_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_freq_ok_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_ok_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_ok_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_freq_ok_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_freq_ok_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label21 = lv_label_create(ui_freq_ok_btn);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "OK");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_cancel_btn = lv_btn_create(ui_freq_change_panel);
    lv_obj_set_width(ui_freq_cancel_btn, 100);
    lv_obj_set_height(ui_freq_cancel_btn, 50);
    lv_obj_set_x(ui_freq_cancel_btn, -48);
    lv_obj_set_y(ui_freq_cancel_btn, -1);
    lv_obj_set_align(ui_freq_cancel_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_freq_cancel_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_freq_cancel_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_cancel_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_cancel_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_freq_cancel_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_freq_cancel_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label22 = lv_label_create(ui_freq_cancel_btn);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Cancel");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rx_freq_panel = lv_obj_create(ui_freq_change_panel);
    lv_obj_set_height(ui_rx_freq_panel, 75);
    lv_obj_set_width(ui_rx_freq_panel, lv_pct(100));
    lv_obj_clear_flag(ui_rx_freq_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rx_freq_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_rx = lv_label_create(ui_rx_freq_panel);
    lv_obj_set_width(ui_label_rx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_rx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_rx, -405);
    lv_obj_set_y(ui_label_rx, 0);
    lv_obj_set_align(ui_label_rx, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_label_rx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_rx, "RX:");
    lv_obj_set_style_text_color(ui_label_rx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_rx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_rx, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rx_freq_ta = lv_textarea_create(ui_rx_freq_panel);
    lv_obj_set_width(ui_rx_freq_ta, 390);
    lv_obj_set_height(ui_rx_freq_ta, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_rx_freq_ta, 35);
    lv_obj_set_y(ui_rx_freq_ta, 0);
    lv_obj_set_align(ui_rx_freq_ta, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_rx_freq_ta, "_.___.___.___");
    lv_textarea_set_placeholder_text(ui_rx_freq_ta, "Placeholder...");
    lv_textarea_set_one_line(ui_rx_freq_ta, true);
    lv_obj_clear_flag(ui_rx_freq_ta, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_rx_freq_ta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rx_freq_ta, &ui_font_number_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rx_freq_ta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rx_freq_ta, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rx_freq_ta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rx_freq_ta, &ui_font_number_60, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_tx_freq_panel = lv_obj_create(ui_freq_change_panel);
    lv_obj_set_height(ui_tx_freq_panel, 75);
    lv_obj_set_width(ui_tx_freq_panel, lv_pct(100));
    lv_obj_set_x(ui_tx_freq_panel, 0);
    lv_obj_set_y(ui_tx_freq_panel, 74);
    lv_obj_clear_flag(ui_tx_freq_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tx_freq_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_tx = lv_label_create(ui_tx_freq_panel);
    lv_obj_set_width(ui_label_tx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_tx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_tx, -405);
    lv_obj_set_y(ui_label_tx, 0);
    lv_obj_set_align(ui_label_tx, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_label_tx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_tx, "TX:");
    lv_obj_set_style_text_color(ui_label_tx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_tx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_tx, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tx_freq_ta = lv_textarea_create(ui_tx_freq_panel);
    lv_obj_set_width(ui_tx_freq_ta, 390);
    lv_obj_set_height(ui_tx_freq_ta, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_tx_freq_ta, 35);
    lv_obj_set_y(ui_tx_freq_ta, 0);
    lv_obj_set_align(ui_tx_freq_ta, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_tx_freq_ta, "_.___.___.___");
    lv_textarea_set_placeholder_text(ui_tx_freq_ta, "Placeholder...");
    lv_textarea_set_one_line(ui_tx_freq_ta, true);
    lv_obj_clear_flag(ui_tx_freq_ta, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_tx_freq_ta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tx_freq_ta, &ui_font_number_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tx_freq_ta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_tx_freq_ta, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_tx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tx_freq_ta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tx_freq_ta, &ui_font_number_60, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_offset_tx_panel = lv_obj_create(ui_freq_change_panel);
    lv_obj_set_height(ui_offset_tx_panel, 75);
    lv_obj_set_width(ui_offset_tx_panel, lv_pct(100));
    lv_obj_set_x(ui_offset_tx_panel, 0);
    lv_obj_set_y(ui_offset_tx_panel, 74);
    lv_obj_add_flag(ui_offset_tx_panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_offset_tx_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_offset_tx_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_tx1 = lv_label_create(ui_offset_tx_panel);
    lv_obj_set_width(ui_label_tx1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_tx1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_tx1, 11);
    lv_obj_set_y(ui_label_tx1, 9);
    lv_label_set_text(ui_label_tx1, "TX Offset:");
    lv_obj_set_style_text_color(ui_label_tx1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_tx1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_tx1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tx_offset_ta = lv_textarea_create(ui_offset_tx_panel);
    lv_obj_set_width(ui_tx_offset_ta, 150);
    lv_obj_set_height(ui_tx_offset_ta, 54);
    lv_obj_set_x(ui_tx_offset_ta, 61);
    lv_obj_set_y(ui_tx_offset_ta, -5);
    lv_obj_set_align(ui_tx_offset_ta, LV_ALIGN_CENTER);

    ui_split_freq_cb = lv_checkbox_create(ui_freq_change_panel);
    lv_checkbox_set_text(ui_split_freq_cb, "Split TX/RX");
    lv_obj_set_width(ui_split_freq_cb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_split_freq_cb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_split_freq_cb, -136);
    lv_obj_set_y(ui_split_freq_cb, -21);
    lv_obj_set_align(ui_split_freq_cb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_split_freq_cb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_split_freq_cb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_split_freq_cb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_split_freq_cb, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_split_freq_cb, lv_color_hex(0x4E4E4E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_split_freq_cb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_freq_ok_btn, ui_event_freq_ok_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_freq_cancel_btn, ui_event_freq_cancel_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rx_freq_ta, ui_event_rx_freq_ta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tx_freq_ta, ui_event_tx_freq_ta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_split_freq_cb, ui_event_split_freq_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_freq_change_panel, ui_event_freq_change_panel, LV_EVENT_ALL, NULL);

}

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_home_screen_screen_init();
    ui_screen_num_freq_pads_screen_init();
    ui_screen_scratchpad_1_screen_init();
    ui_screen_scratchpad_2_screen_init();
    ui_screen_scratchpad_3_screen_init();
    ui_screen_scratchpad_4_screen_init();
    ui_screen_scratchpad_5_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_home_screen);
}
