// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenHT_UI

#include "../ui.h"

void ui_main_screen_screen_init(void)
{
    ui_main_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_main_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main_screen, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_main_screen, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_main_panel = lv_obj_create(ui_main_screen);
    lv_obj_set_width(ui_main_panel, lv_pct(100));
    lv_obj_set_height(ui_main_panel, lv_pct(100));
    lv_obj_set_align(ui_main_panel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_main_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_main_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_main_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_panel = lv_obj_create(ui_main_panel);
    lv_obj_set_height(ui_header_panel, 100);
    lv_obj_set_width(ui_header_panel, lv_pct(100));
    lv_obj_set_align(ui_header_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_header_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_panel, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_header_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_title_image = lv_img_create(ui_header_panel);
    lv_img_set_src(ui_title_image, &ui_img_openht_logo_w_png);
    lv_obj_set_width(ui_title_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_title_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_title_image, 0);
    lv_obj_set_y(ui_title_image, 1);
    lv_obj_set_align(ui_title_image, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_title_image, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_title_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery_image = lv_img_create(ui_header_panel);
    lv_img_set_src(ui_battery_image, &ui_img_152149816);
    lv_obj_set_width(ui_battery_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_battery_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_battery_image, -20);
    lv_obj_set_y(ui_battery_image, 5);
    lv_obj_set_align(ui_battery_image, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_battery_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_battery_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_signal_strenth_image = lv_img_create(ui_header_panel);
    lv_img_set_src(ui_signal_strenth_image, &ui_img_492966190);
    lv_obj_set_width(ui_signal_strenth_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_signal_strenth_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_signal_strenth_image, 385);
    lv_obj_set_y(ui_signal_strenth_image, 2);
    lv_obj_add_flag(ui_signal_strenth_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_signal_strenth_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_header_callsign_button = lv_btn_create(ui_header_panel);
    lv_obj_set_height(ui_header_callsign_button, 50);
    lv_obj_set_width(ui_header_callsign_button, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_header_callsign_button, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_header_callsign_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_header_callsign_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_callsign_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_header_callsign_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_callsign_label = lv_label_create(ui_header_callsign_button);
    lv_obj_set_width(ui_header_callsign_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_header_callsign_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_header_callsign_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_header_callsign_label, "Callsign: ");
    lv_obj_set_style_text_color(ui_header_callsign_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_header_callsign_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_header_callsign_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_mode_button = lv_btn_create(ui_header_panel);
    lv_obj_set_height(ui_header_mode_button, 50);
    lv_obj_set_width(ui_header_mode_button, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_header_mode_button, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_header_mode_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_header_mode_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_mode_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_header_mode_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_mode_label = lv_label_create(ui_header_mode_button);
    lv_obj_set_width(ui_header_mode_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_header_mode_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_header_mode_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_header_mode_label, "Mode: ");
    lv_obj_set_style_text_color(ui_header_mode_label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_header_mode_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_header_mode_label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_header_settings_button = lv_btn_create(ui_header_panel);
    lv_obj_set_width(ui_header_settings_button, 60);
    lv_obj_set_height(ui_header_settings_button, 50);
    lv_obj_add_flag(ui_header_settings_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_header_settings_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_header_settings_button, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_header_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_header_settings_button);
    lv_img_set_src(ui_Image1, &ui_img_gear_w_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -5);
    lv_obj_set_align(ui_Image1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_vfo_label = lv_label_create(ui_main_panel);
    lv_obj_set_width(ui_vfo_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vfo_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vfo_label, 0);
    lv_obj_set_y(ui_vfo_label, 210);
    lv_obj_set_align(ui_vfo_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_vfo_label, "VFO");
    lv_obj_set_style_text_color(ui_vfo_label, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vfo_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vfo_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vfo_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_about_btn = lv_btn_create(ui_main_panel);
    lv_obj_set_width(ui_about_btn, 130);
    lv_obj_set_height(ui_about_btn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_about_btn, 339);
    lv_obj_set_y(ui_about_btn, -259);
    lv_obj_set_align(ui_about_btn, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_about_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_about_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_about_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_about_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_about_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_about_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label5 = lv_label_create(ui_about_btn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "About...");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vfo_panel = lv_obj_create(ui_main_panel);
    lv_obj_set_width(ui_vfo_panel, 450);
    lv_obj_set_height(ui_vfo_panel, 125);
    lv_obj_set_x(ui_vfo_panel, 0);
    lv_obj_set_y(ui_vfo_panel, 250);
    lv_obj_set_align(ui_vfo_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_vfo_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_vfo_panel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_vfo_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vfo_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_vfo_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_vfo_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_rx = lv_label_create(ui_vfo_panel);
    lv_obj_set_width(ui_label_test_rx, 400);
    lv_obj_set_height(ui_label_test_rx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_label_test_rx, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_label_test_rx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_test_rx, "000.000.000");
    lv_obj_set_style_text_color(ui_label_test_rx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_test_rx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label_test_rx, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_test_rx, &ui_font_number_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_test_tx = lv_label_create(ui_vfo_panel);
    lv_obj_set_width(ui_label_test_tx, 400);
    lv_obj_set_height(ui_label_test_tx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_test_tx, 0);
    lv_obj_set_y(ui_label_test_tx, 50);
    lv_obj_set_align(ui_label_test_tx, LV_ALIGN_TOP_MID);
    lv_label_set_long_mode(ui_label_test_tx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_test_tx, "000.000.000");
    lv_obj_set_style_text_color(ui_label_test_tx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_test_tx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_label_test_tx, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_test_tx, &ui_font_number_50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ptt_btn = lv_btn_create(ui_main_panel);
    lv_obj_set_width(ui_ptt_btn, 145);
    lv_obj_set_height(ui_ptt_btn, 123);
    lv_obj_set_x(ui_ptt_btn, 1);
    lv_obj_set_y(ui_ptt_btn, 183);
    lv_obj_set_align(ui_ptt_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ptt_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ptt_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ptt_btn, 400, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ptt_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ptt_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ptt_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ptt_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ptt_btn, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ptt_btn, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ptt_btn, lv_color_hex(0xD4001D), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ptt_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label3 = lv_label_create(ui_ptt_btn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "PTT");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vol_label = lv_label_create(ui_main_panel);
    lv_obj_set_width(ui_vol_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_vol_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_vol_label, -15);
    lv_obj_set_y(ui_vol_label, -68);
    lv_obj_set_align(ui_vol_label, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_vol_label, "Volume Control");
    lv_obj_set_style_text_color(ui_vol_label, lv_color_hex(0xD2CDC8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_vol_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_vol_label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_vol_label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_vol_slider = lv_slider_create(ui_main_panel);
    lv_slider_set_value(ui_vol_slider, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_vol_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_vol_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_vol_slider, 350);
    lv_obj_set_height(ui_vol_slider, 20);
    lv_obj_set_x(ui_vol_slider, 0);
    lv_obj_set_y(ui_vol_slider, -22);
    lv_obj_set_align(ui_vol_slider, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_bg_color(ui_vol_slider, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vol_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_vol_slider, lv_color_hex(0x1E242D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_vol_slider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_vol_slider, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_vol_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_vol_slider, lv_color_hex(0x37B9F5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vol_slider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_vol_slider, lv_color_hex(0x1464F0), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_vol_slider, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_vol_slider, lv_color_hex(0x5F6464), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_vol_slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_vol_slider, lv_color_hex(0x3C424B), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_vol_slider, LV_GRAD_DIR_VER, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_vol_slider, lv_color_hex(0x373C46), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_vol_slider, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_vol_slider, 2, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_vol_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_vol_slider, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_vol_slider, lv_color_hex(0x0096FF), LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_vol_slider, 255, LV_PART_KNOB | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_vol_slider, 4, LV_PART_KNOB | LV_STATE_PRESSED);

    lv_obj_add_event_cb(ui_title_image, ui_event_title_image, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_header_callsign_button, ui_event_header_callsign_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_header_mode_button, ui_event_header_mode_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_header_settings_button, ui_event_header_settings_button, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_about_btn, ui_event_about_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vfo_panel, ui_event_vfo_panel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ptt_btn, ui_event_ptt_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_vol_slider, ui_event_vol_slider, LV_EVENT_ALL, NULL);

}
