// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: OpenHT_UI

#include "../ui.h"

void ui_screen_scratchpad_5_screen_init(void)
{
    ui_screen_scratchpad_5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen_scratchpad_5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_freq_change_panel = lv_obj_create(ui_screen_scratchpad_5);
    lv_obj_set_width(ui_freq_change_panel, 480);
    lv_obj_set_height(ui_freq_change_panel, 430);
    lv_obj_set_x(ui_freq_change_panel, 0);
    lv_obj_set_y(ui_freq_change_panel, 48);
    lv_obj_set_align(ui_freq_change_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_freq_change_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_change_panel, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_freq_change_panel, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_freq_change_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_freq_change_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_freq_change_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_freq_change_panel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_freq_change_panel, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_ok_btn = lv_btn_create(ui_freq_change_panel);
    lv_obj_set_width(ui_freq_ok_btn, 100);
    lv_obj_set_height(ui_freq_ok_btn, 50);
    lv_obj_set_x(ui_freq_ok_btn, 66);
    lv_obj_set_y(ui_freq_ok_btn, -1);
    lv_obj_set_align(ui_freq_ok_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_freq_ok_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_freq_ok_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_ok_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_ok_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_freq_ok_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_freq_ok_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label21 = lv_label_create(ui_freq_ok_btn);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "OK");
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_freq_cancel_btn = lv_btn_create(ui_freq_change_panel);
    lv_obj_set_width(ui_freq_cancel_btn, 100);
    lv_obj_set_height(ui_freq_cancel_btn, 50);
    lv_obj_set_x(ui_freq_cancel_btn, -48);
    lv_obj_set_y(ui_freq_cancel_btn, -1);
    lv_obj_set_align(ui_freq_cancel_btn, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_freq_cancel_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_freq_cancel_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_freq_cancel_btn, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_freq_cancel_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_freq_cancel_btn, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_freq_cancel_btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Label22 = lv_label_create(ui_freq_cancel_btn);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Cancel");
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rx_freq_panel = lv_obj_create(ui_freq_change_panel);
    lv_obj_set_height(ui_rx_freq_panel, 75);
    lv_obj_set_width(ui_rx_freq_panel, lv_pct(100));
    lv_obj_clear_flag(ui_rx_freq_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_rx_freq_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_rx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_rx = lv_label_create(ui_rx_freq_panel);
    lv_obj_set_width(ui_label_rx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_rx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_rx, -405);
    lv_obj_set_y(ui_label_rx, 0);
    lv_obj_set_align(ui_label_rx, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_label_rx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_rx, "RX:");
    lv_obj_set_style_text_color(ui_label_rx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_rx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_rx, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rx_freq_ta = lv_textarea_create(ui_rx_freq_panel);
    lv_obj_set_width(ui_rx_freq_ta, 390);
    lv_obj_set_height(ui_rx_freq_ta, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_rx_freq_ta, 35);
    lv_obj_set_y(ui_rx_freq_ta, 0);
    lv_obj_set_align(ui_rx_freq_ta, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_rx_freq_ta, "_.___.___.___");
    lv_textarea_set_placeholder_text(ui_rx_freq_ta, "Placeholder...");
    lv_textarea_set_one_line(ui_rx_freq_ta, true);
    lv_obj_clear_flag(ui_rx_freq_ta, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_rx_freq_ta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rx_freq_ta, &ui_font_number_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rx_freq_ta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rx_freq_ta, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rx_freq_ta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rx_freq_ta, &ui_font_number_60, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_tx_freq_panel = lv_obj_create(ui_freq_change_panel);
    lv_obj_set_height(ui_tx_freq_panel, 75);
    lv_obj_set_width(ui_tx_freq_panel, lv_pct(100));
    lv_obj_set_x(ui_tx_freq_panel, 0);
    lv_obj_set_y(ui_tx_freq_panel, 74);
    lv_obj_clear_flag(ui_tx_freq_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tx_freq_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_tx_freq_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_tx = lv_label_create(ui_tx_freq_panel);
    lv_obj_set_width(ui_label_tx, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_tx, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_tx, -405);
    lv_obj_set_y(ui_label_tx, 0);
    lv_obj_set_align(ui_label_tx, LV_ALIGN_RIGHT_MID);
    lv_label_set_long_mode(ui_label_tx, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_label_tx, "TX:");
    lv_obj_set_style_text_color(ui_label_tx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_tx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_tx, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tx_freq_ta = lv_textarea_create(ui_tx_freq_panel);
    lv_obj_set_width(ui_tx_freq_ta, 390);
    lv_obj_set_height(ui_tx_freq_ta, LV_SIZE_CONTENT);    /// 84
    lv_obj_set_x(ui_tx_freq_ta, 35);
    lv_obj_set_y(ui_tx_freq_ta, 0);
    lv_obj_set_align(ui_tx_freq_ta, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_tx_freq_ta, "_.___.___.___");
    lv_textarea_set_placeholder_text(ui_tx_freq_ta, "Placeholder...");
    lv_textarea_set_one_line(ui_tx_freq_ta, true);
    lv_obj_clear_flag(ui_tx_freq_ta, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_color(ui_tx_freq_ta, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tx_freq_ta, &ui_font_number_60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_tx_freq_ta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_tx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_tx_freq_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_tx_freq_ta, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_tx_freq_ta, lv_color_hex(0x37B9F5), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tx_freq_ta, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tx_freq_ta, &ui_font_number_60, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_offset_tx_panel = lv_obj_create(ui_freq_change_panel);
    lv_obj_set_height(ui_offset_tx_panel, 75);
    lv_obj_set_width(ui_offset_tx_panel, lv_pct(100));
    lv_obj_set_x(ui_offset_tx_panel, 0);
    lv_obj_set_y(ui_offset_tx_panel, 74);
    lv_obj_add_flag(ui_offset_tx_panel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_offset_tx_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_offset_tx_panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_offset_tx_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_label_tx1 = lv_label_create(ui_offset_tx_panel);
    lv_obj_set_width(ui_label_tx1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label_tx1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label_tx1, 11);
    lv_obj_set_y(ui_label_tx1, 9);
    lv_label_set_text(ui_label_tx1, "TX Offset:");
    lv_obj_set_style_text_color(ui_label_tx1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_label_tx1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_tx1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tx_offset_ta = lv_textarea_create(ui_offset_tx_panel);
    lv_obj_set_width(ui_tx_offset_ta, 150);
    lv_obj_set_height(ui_tx_offset_ta, 54);
    lv_obj_set_x(ui_tx_offset_ta, 61);
    lv_obj_set_y(ui_tx_offset_ta, -5);
    lv_obj_set_align(ui_tx_offset_ta, LV_ALIGN_CENTER);

    ui_split_freq_cb = lv_checkbox_create(ui_freq_change_panel);
    lv_checkbox_set_text(ui_split_freq_cb, "Split TX/RX");
    lv_obj_set_width(ui_split_freq_cb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_split_freq_cb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_split_freq_cb, -136);
    lv_obj_set_y(ui_split_freq_cb, -21);
    lv_obj_set_align(ui_split_freq_cb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_split_freq_cb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_split_freq_cb, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_split_freq_cb, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_split_freq_cb, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_split_freq_cb, lv_color_hex(0x4E4E4E), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_split_freq_cb, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_freq_change_panel);
    lv_obj_set_width(ui_Panel2, 381);
    lv_obj_set_height(ui_Panel2, 76);
    lv_obj_set_x(ui_Panel2, -20);
    lv_obj_set_y(ui_Panel2, 58);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ctcss_dropdown = lv_dropdown_create(ui_Panel2);
    lv_dropdown_set_options(ui_ctcss_dropdown, "");
    lv_obj_set_width(ui_ctcss_dropdown, 162);
    lv_obj_set_height(ui_ctcss_dropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ctcss_dropdown, 35);
    lv_obj_set_y(ui_ctcss_dropdown, 0);
    lv_obj_set_align(ui_ctcss_dropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ctcss_dropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_ctcss_dropdown, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ctcss_dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ctcss_dropdown, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ctcss_dropdown, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ctcss_dropdown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ctcss_dropdown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_ctcss_dropdown, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ctcss_dropdown, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_ctcss_dropdown), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_ctcss_dropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_ctcss_dropdown), &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_ctcss_dropdown), lv_color_hex(0x464B55),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_ctcss_dropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_ctcss_dropdown), lv_color_hex(0x191C26),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_ctcss_dropdown), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -117);
    lv_obj_set_y(ui_Label23, 10);
    lv_obj_set_align(ui_Label23, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label23, "CTCSS Tone:");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label23, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_freq_ok_btn, ui_event_freq_ok_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_freq_cancel_btn, ui_event_freq_cancel_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_rx_freq_ta, ui_event_rx_freq_ta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tx_freq_ta, ui_event_tx_freq_ta, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_split_freq_cb, ui_event_split_freq_cb, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_freq_change_panel, ui_event_freq_change_panel, LV_EVENT_ALL, NULL);

}
